apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-01-26T17:45:37Z"
  generation: 1
  labels:
    app: grafana-app
  name: grafana-app
  namespace: default
  resourceVersion: "9438"
  uid: 7e4b31e9-6c01-4a5d-b458-6557a294f1f0
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana-app
    spec:
      containers:
      - image: grafana/grafana-enterprise
        imagePullPolicy: Always
        name: grafana-enterprise
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
