apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-01-26T17:45:46Z"
  labels:
    app: grafana-app
  name: grafana-app
  namespace: default
  resourceVersion: "9460"
  uid: 6fba31ef-0102-4bf0-8751-7bb9391f7317
spec:
  clusterIP: 10.108.216.131
  clusterIPs:
  - 10.108.216.131
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32723
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana-app
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
